# Generated by Django 2.2 on 2021-08-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('react', 'react'), ('html', 'html'), ('javascipt', 'javascipt'), ('python', 'python'), ('css', 'css'), ('django', 'django')], max_length=80, null=True)),
                ('dt_created', models.DateField()),
            ],
        ),
    ]
