# Generated by Django 2.2 on 2021-12-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('css', 'css'), ('html', 'html'), ('django', 'django'), ('javascript', 'javascript'), ('react', 'react'), ('python', 'python')], max_length=80, null=True),
        ),
    ]
