# Generated by Django 2.2 on 2021-08-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descirption',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('react', 'react'), ('css', 'css'), ('html', 'html'), ('javascipt', 'javascipt'), ('django', 'django'), ('python', 'python')], max_length=80, null=True),
        ),
    ]
