# Generated by Django 2.2 on 2021-08-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210809_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descirption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('react', 'react'), ('django', 'django'), ('python', 'python'), ('html', 'html'), ('javascipt', 'javascipt'), ('css', 'css')], max_length=80, null=True),
        ),
    ]
