# Generated by Django 2.2 on 2021-12-22 06:56

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20211220_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', django_summernote.fields.SummernoteTextField(default='')),
                ('type', models.CharField(choices=[('react', 'react'), ('algorithm', 'algorithm'), ('css', 'css'), ('DB', 'DB'), ('python', 'python'), ('html', 'html'), ('django', 'django'), ('javascript', 'javascript'), ('node', 'node')], default='css', max_length=80, null=True)),
                ('description', models.CharField(default='', max_length=200)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('react', 'react'), ('algorithm', 'algorithm'), ('css', 'css'), ('DB', 'DB'), ('python', 'python'), ('html', 'html'), ('django', 'django'), ('javascript', 'javascript'), ('node', 'node')], default='css', max_length=80, null=True),
        ),
    ]
