# Generated by Django 2.2 on 2021-12-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20211222_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('algorithm', 'algorithm'), ('react', 'react'), ('node', 'node'), ('DB', 'DB'), ('html', 'html'), ('javascript', 'javascript'), ('python', 'python'), ('django', 'django'), ('css', 'css')], default='css', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='project_content',
            name='type',
            field=models.CharField(choices=[('algorithm', 'algorithm'), ('react', 'react'), ('node', 'node'), ('DB', 'DB'), ('html', 'html'), ('javascript', 'javascript'), ('python', 'python'), ('django', 'django'), ('css', 'css')], default='css', max_length=80, null=True),
        ),
    ]
