# Generated by Django 2.2 on 2021-08-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210809_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('html', 'html'), ('react', 'react'), ('python', 'python'), ('django', 'django'), ('css', 'css'), ('javascipt', 'javascipt')], max_length=80, null=True),
        ),
    ]
