# Generated by Django 2.2 on 2021-12-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20211215_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('react', 'react'), ('html', 'html'), ('python', 'python'), ('css', 'css'), ('javascript', 'javascript'), ('django', 'django')], max_length=80, null=True),
        ),
    ]
