# Generated by Django 2.2 on 2021-12-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20211215_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('python', 'python'), ('javascript', 'javascript'), ('django', 'django'), ('css', 'css'), ('html', 'html'), ('react', 'react')], default='', max_length=80, null=True),
        ),
    ]
