# Generated by Django 2.2 on 2021-12-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20211222_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('react', 'react'), ('python', 'python'), ('DB', 'DB'), ('algorithm', 'algorithm'), ('node', 'node'), ('html', 'html'), ('javascript', 'javascript'), ('django', 'django'), ('css', 'css')], default='css', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='project_content',
            name='type',
            field=models.CharField(choices=[('react', 'react'), ('python', 'python'), ('DB', 'DB'), ('algorithm', 'algorithm'), ('node', 'node'), ('html', 'html'), ('javascript', 'javascript'), ('django', 'django'), ('css', 'css')], default='css', max_length=80, null=True),
        ),
    ]
