# Generated by Django 2.2 on 2021-08-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210813_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('django', 'django'), ('javascript', 'javascript'), ('python', 'python'), ('css', 'css'), ('html', 'html'), ('react', 'react')], max_length=80, null=True),
        ),
    ]
