# Generated by Django 2.2 on 2021-12-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20211215_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('react', 'react'), ('algorithm', 'algorithm'), ('python', 'python'), ('css', 'css'), ('django', 'django'), ('DB', 'DB'), ('html', 'html'), ('javascript', 'javascript')], default='', max_length=80, null=True),
        ),
    ]
