# Generated by Django 2.2 on 2021-12-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20211222_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_content',
            name='type',
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('javascript', 'javascript'), ('css', 'css'), ('django', 'django'), ('react', 'react'), ('python', 'python'), ('DB', 'DB'), ('html', 'html'), ('algorithm', 'algorithm'), ('node', 'node')], default='css', max_length=80, null=True),
        ),
    ]
