# Generated by Django 2.2 on 2021-12-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20211222_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('django', 'django'), ('css', 'css'), ('react', 'react'), ('algorithm', 'algorithm'), ('html', 'html'), ('node', 'node'), ('DB', 'DB'), ('python', 'python'), ('javascript', 'javascript')], default='css', max_length=80, null=True),
        ),
    ]
