# Generated by Django 2.2 on 2021-12-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20211216_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('html', 'html'), ('python', 'python'), ('css', 'css'), ('django', 'django'), ('algorithm', 'algorithm'), ('react', 'react'), ('DB', 'DB'), ('javascript', 'javascript')], default='css', max_length=80, null=True),
        ),
    ]
