# Generated by Django 2.2 on 2021-12-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20211216_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('react', 'react'), ('html', 'html'), ('javascript', 'javascript'), ('DB', 'DB'), ('algorithm', 'algorithm'), ('django', 'django'), ('css', 'css'), ('python', 'python')], default='css', max_length=80, null=True),
        ),
    ]
